### ISSUE TITLE
After updating to 5.2.2 internal enrichment  connectors give error: nonetype object is not subscriptable

### ISSUE THREAD

**Issue by AlexSanchezN** [OpenCTI-Platform/connectors#642]
## Description
I've upgraded to 5.2.2. Two of my ip internal enrichment connectors(abuseip, and ipinfo) give the error: nonetype object is not subscriptable.
The observable that I try to enrich, has a TLP label (have seen other isue where that was a temporary measure to make enrichment work)

## Environment

1. OS (where OpenCTI server runs): Ubuntu
2. OpenCTI version: 5.2.2
3. OpenCTI client: Both
4. Baremetal installation, not docker

## Expected Output

Some information about the IP

## Actual Output

The error above
 
## Additional information

Error in connector log:

INFO:root:Reporting work update_received opencti-work--95af576e-3e2e-4307-912c-602b60255ebf
INFO:root:Reading StixCyberObservable {30e05bc5-044b-4179-8d58-bafb75aa3d9f}.
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pycti/connector/opencti_connector_helper.py", line 163, in _data_handler
    message = self.callback(json_data["event"])
  File "abuseipdb.py", line 62, in _process_message
    for marking_definition in observable.get("objectMarking", []):
AttributeError: 'NoneType' object has no attribute 'get'

## Screenshots (optional)
![image](https://user-images.githubusercontent.com/6607235/159898389-fe2bd0ca-5285-46f2-94ed-d37dd9e5e392.png)

**Comment by nor3th** [comment]
Hey @AlexSanchezN 

Looks like the connectors don't have the permission to request the observables. Similar to https://github.com/OpenCTI-Platform/connectors/issues/634

Regards

**Comment by SamuelHassine** [comment]
@AlexSanchezN Are you sure this behavior is coming after the upgrade? Your description is the "expected" behavior, if the connector role does not have the "bypass" capability, you have to create a group that has access to the appropriate markings and include the connector user in it. But this behavior is at least since version > 4.1.

Please can you tell me what was your original platform version (from which version do you upgrade to 5.2.2?).

Thanks.
