### ISSUE TITLE
[Mandiant] Mandiant connector stopped importing data 

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#1547]
## Description

The Mandiant connector worked for several days then started outputting errors and no longer imported anything.

Different error message appear : 

`Traceback (most recent call last): File "/opt/connector/base.py", line 485, in _run for item in collection_api(**parameters): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: MandiantAPI.vulnerabilities() got an unexpected keyword argument 'sort_order' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/opt/connector/base.py", line 413, in run self._run(collection, work_id) File "/opt/connector/base.py", line 503, in _run state[collection][STATE_START] = item["publish_date"] ^^^^ UnboundLocalError: cannot access local variable 'item' where it is not associated with a value`

`Error pinging the API`

`An unknown error occurred, code: 400`

I let you check the log of the connector

## Environment

5.11.13

**Comment by gyaansastra** [comment]
After upgrading to 5.11.14

ERROR An unknown error occurred, code: 400. | timestamp=2023-11-21T06:41:05.413540Z name=mandiant-api
ERROR An unknown error occurred, code: 400 | timestamp=2023-11-21T06:41:07.414018Z name=pycti.connector
ERROR Traceback (most recent call last):
  File "/opt/connector/base.py", line 413, in run
    self._run(collection, work_id)
  File "/opt/connector/base.py", line 512, in _run
    raise error
  File "/opt/connector/base.py", line 485, in _run
    for item in collection_api(**parameters):
  File "/opt/connector/api.py", line 136, in _process
    response = self._query(url, self.modes.get(mode))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/connector/api.py", line 121, in _query
    raise ValueError(f"An unknown error occurred, code: {response.status_code}")
ValueError: An unknown error occurred, code: 400
 | timestamp=2023-11-21T06:41:07.415356Z name=pycti.connector
 
Only getting indicators, malware, and Intrusion sets. However, Reports and other information are not coming. For reference the docker-compose extract
 
 version: '3'
services:
  connector-mandiant:
    image: opencti/connector-mandiant:5.11.14
    environment:
      - OPENCTI_URL=http://localhost
      - OPENCTI_TOKEN=ChangeMe
      - CONNECTOR_ID=ChangeMe
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Mandiant
      - CONNECTOR_SCOPE=mandiant
      - CONNECTOR_CONFIDENCE_LEVEL=80
      - CONNECTOR_UPDATE_EXISTING_DATA=false
      - CONNECTOR_LOG_LEVEL=error
      - MANDIANT_API_V4_KEY_ID=
      - MANDIANT_API_V4_KEY_SECRET=
      #Additional Params
      - MANDIANT_INTERVAL=1 #Number of the days between each collection
      - MANDIANT_IMPORT_START_DATE=2023-05-05
      - MANDIANT_INDICATOR_MINIMUM_SCORE=60
      #Import Types
      - MANDIANT_IMPORT_ACTORS=True
      - MANDIANT_IMPORT_REPORTS=True
      - MANDIANT_IMPORT_MALWARES=True
      - MANDIANT_IMPORT_CAMPAIGNS=True
      - MANDIANT_IMPORT_INDICATORS=True
      - MANDIANT_IMPORT_VULNERABILITIES=True
      - MANDIANT_ACTOR_PROFILE_REPORT=True
      - MANDIANT_COUNTRY_PROFILE_REPORT=True
      - MANDIANT_EXECUTIVE_PERSPECTIVE_REPORT=True
      - MANDIANT_INDUSTRY_REPORTING_REPORT=True
      - MANDIANT_NETWORK_ACTIVITY_REPORT=True
      - MANDIANT_THREAT_ACTIVITY_ALERT_REPORT=True
      - MANDIANT_THREAT_ACTIVITY_REPORT=True
      - MANDIANT_TRENDS_AND_FORECASTING_REPORT=True
      - MANDIANT_VULNERABILITY_REPORT=False #Disable
      #Import Report Types
      - MANDIANT_ACTOR_PROFILE_REPORT_TYPE=actor-profile
      - MANDIANT_COUNTRY_PROFILE_REPORT_TYPE=country-profile
      - MANDIANT_EXECUTIVE_PERSPECTIVE_REPORT_TYPE=executive-perspective
      - MANDIANT_MALWARE_PROFILE_REPORT_TYPE=malware-profile
      - MANDIANT_NETWORK_ACTIVITY_REPORT_TYPE=network-activity
      - MANDIANT_THREAT_ACTIVITY_ALERT_REPORT_TYPE=threat-alert
      - MANDIANT_THREAT_ACTIVITY_REPORT_TYPE=threat-activity
      - MANDIANT_TRENDS_AND_FORECASTING_REPORT_TYPE=trends-forecasting
    restart: always
