### ISSUE TITLE
fix(Intel 471v2): TypeError __init__ unexpected keyword arg 'proxy'

### ISSUE THREAD

**Issue by fruitcakej** [OpenCTI-Platform/connectors#6912]
## Description
After migration to v.7 the Intel471 V2 connector stopped working. The connector reports variable for proxy as unknown. This variable exists in documentation.

## Environment
1. On-prem 7.260701.0

## Actual output
`{"timestamp": "2026-07-03T12:30:13.424030Z", "level": "INFO", "name": "Intel471", "message": "Starting PingAlive thread"}
Traceback (most recent call last):
  File "/opt/opencti-intel471_v2/main.py", line 21, in <module>
    connector = Intel471Connector(config=settings, helper=helper)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-intel471_v2/intel471/connector.py", line 31, in __init__
    client_wrapper: ClientWrapper = get_client(
                                    ^^^^^^^^^^^
  File "/opt/opencti-intel471_v2/intel471/backend.py", line 57, in get_client
    titan_client.Configuration(**config_kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Configuration.__init__() got an unexpected keyword argument 'proxy'`

## Additional information
Was working on 6.9.28
Related : https://github.com/OpenCTI-Platform/connectors/issues/6141

**Comment by Powlinett** [comment]
Titan Client doesn't seem to support proxy at all:
https://github.com/intel471/titan-client-python/blob/main/titan_client/configuration.py#L203

Although, Verity471 client seems to handle it correctly:
https://github.com/intel471/verity471-python/blob/main/verity471/configuration.py#L339

The migration guide in connector's README seems to encourage users to use Verity471 over Titan:
https://github.com/OpenCTI-Platform/connectors/blob/master/external-import/intel471_v2/README.md#-migration-guide-titan-to-verity471

NB: The unit tests in `intel471_v2` connector don't actually test the instantiation of `titan_client.Configuration` as the tests heavily rely on mocks:
https://github.com/OpenCTI-Platform/connectors/commit/f50f36eb646eaa55a610906693a5475b01eb0f76
