### PR TITLE
fix(intel471_v2): fix proxy for titan (#6912)

### LINKED ISSUE #6912: fix(Intel 471v2): TypeError __init__ unexpected keyword arg 'proxy'
## Description
After migration to v.7 the Intel471 V2 connector stopped working. The connector reports variable for proxy as unknown. This variable exists in documentation.

## Environment
1. On-prem 7.260701.0

## Actual output
`{"timestamp": "2026-07-03T12:30:13.424030Z", "level": "INFO", "name": "Intel471", "message": "Starting PingAlive thread"}
Traceback (most recent call last):
  File "/opt/opencti-intel471_v2/main.py", line 21, in <module>
    connector = Intel471Connector(config=settings, helper=helper)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-intel471_v2/intel471/connector.py", line 31, in __init__
    client_wrapper: ClientWrapper = get_client(
                                    ^^^^^^^^^^^
  File "/opt/opencti-intel471_v2/intel471/backend.py", line 57, in get_client
    titan_client.Configuration(**config_kwargs),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Configuration.__init__() got an unexpected keyword argument 'proxy'`

## Additional information
Was working on 6.9.28
Related : https://github.com/OpenCTI-Platform/connectors/issues/6141

### PR DESCRIPTION
**Pull request by throuxel**
### Proposed changes

* Fix proxy init for titan
* Add test

### Related issues

* Closes: #6912 

### Checklist

- [x] I consider the submitted work as finished
- [x] I have signed my commits using GPG key.
- [x] I tested the code for its functionality using different use cases
- [x] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

**Review by Powlinett — APPROVED** [review]
👌
